// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-DO8YouHlZK3DQmlpWeVa_YkWMzFTkts',
    appId: '1:733551193068:web:083110bc410d969ded2ec9',
    messagingSenderId: '733551193068',
    projectId: 'kids-stories-67585',
    authDomain: 'kids-stories-67585.firebaseapp.com',
    storageBucket: 'kids-stories-67585.appspot.com',
    measurementId: 'G-11EV25LQP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhRnTI5fGUbDpAKLTrY3runTvrd8RdPPI',
    appId: '1:733551193068:android:f160da49605ec31ded2ec9',
    messagingSenderId: '733551193068',
    projectId: 'kids-stories-67585',
    storageBucket: 'kids-stories-67585.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAzmUIqOnyI6YLW9ETpfA6x4mxvpMCdSI',
    appId: '1:733551193068:ios:3e19bde9d3d9bd5ced2ec9',
    messagingSenderId: '733551193068',
    projectId: 'kids-stories-67585',
    storageBucket: 'kids-stories-67585.appspot.com',
    androidClientId: '733551193068-26toa4fapqnfunr3e1c4nb6aut8h7ecd.apps.googleusercontent.com',
    iosClientId: '733551193068-24cgndhi49s4pvvoo41t3d64bdifq2bl.apps.googleusercontent.com',
    iosBundleId: 'com.example.kidsStories',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAzmUIqOnyI6YLW9ETpfA6x4mxvpMCdSI',
    appId: '1:733551193068:ios:de5ce7316c511a4ced2ec9',
    messagingSenderId: '733551193068',
    projectId: 'kids-stories-67585',
    storageBucket: 'kids-stories-67585.appspot.com',
    androidClientId: '733551193068-26toa4fapqnfunr3e1c4nb6aut8h7ecd.apps.googleusercontent.com',
    iosClientId: '733551193068-cf53d4565e6qpsbppiue9kuj835lf8a2.apps.googleusercontent.com',
    iosBundleId: 'com.example.kidsStories.RunnerTests',
  );
}
